### ISSUE TITLE
presented example is not working

### ISSUE THREAD

**Issue by hajovonta** [astahlman/ob-async#94]
When trying the example presented on the readme page, I got no results.
Instead, the *Warnings* buffer pops up with a message:

```
Warning (emacs): ob-async-org-babel-execute-src-block is no longer needed in org-ctrl-c-ctrl-c-hook
```

it seems the source was never executed.

**Comment by wmealing** [comment]
Just to be clear this is the one in the animated gif ?

You might have some older emacs configuration code hooking into org-ctrl-c-ctrl-c-hook.  Preventing it from working.

Take a look through your config to find out where its being hooked from, remove that and see if the issue presents itself.

I have just tested current ob-async with a clean config on emacs 28 and it works correctly.

The problem is most likely in your local configuration.

**Comment by hajovonta** [comment]
Thanks for taking your time to verify it. I don't know why, but it now works. My guess is that in the meantime I updated packages, config and Emacs several times, perhaps the problematic config/package was overwritten with a correct one.

**Comment by wmealing** [comment]
Emacs can be a harsh tool.  Glad its working for you now, do you want to close up this issue (I can't.. but I assume you can).

**Comment by hajovonta** [comment]
Yes, let's close this. Thanks again for looking into it.
